import WebSocket from 'ws';
import crypto from 'crypto';

export interface EdgeVoice {
  name: string;
  shortName: string;
  gender: 'Female' | 'Male';
  locale: 'bn-BD' | 'bn-IN' | 'en-US' | 'en-GB' | 'hi-IN' | string;
  friendlyName: string;
}

export const POPULAR_EDGE_VOICES: EdgeVoice[] = [
  // Bengali Voices
  { name: 'Microsoft Server Speech Text to Speech Voice (bn-BD, PradeepNeural)', shortName: 'bn-BD-PradeepNeural', gender: 'Male', locale: 'bn-BD', friendlyName: 'Pradeep (Bengali Bangladesh - Male)' },
  { name: 'Microsoft Server Speech Text to Speech Voice (bn-BD, NabanitaNeural)', shortName: 'bn-BD-NabanitaNeural', gender: 'Female', locale: 'bn-BD', friendlyName: 'Nabanita (Bengali Bangladesh - Female)' },
  { name: 'Microsoft Server Speech Text to Speech Voice (bn-IN, BashkarNeural)', shortName: 'bn-IN-BashkarNeural', gender: 'Male', locale: 'bn-IN', friendlyName: 'Bashkar (Bengali India - Male)' },
  { name: 'Microsoft Server Speech Text to Speech Voice (bn-IN, TanishaaNeural)', shortName: 'bn-IN-TanishaaNeural', gender: 'Female', locale: 'bn-IN', friendlyName: 'Tanishaa (Bengali India - Female)' },
  
  // English Voices
  { name: 'Microsoft Server Speech Text to Speech Voice (en-US, AvaMultilingualNeural)', shortName: 'en-US-AvaMultilingualNeural', gender: 'Female', locale: 'en-US', friendlyName: 'Ava Multilingual (English US - Natural Female)' },
  { name: 'Microsoft Server Speech Text to Speech Voice (en-US, AndrewMultilingualNeural)', shortName: 'en-US-AndrewMultilingualNeural', gender: 'Male', locale: 'en-US', friendlyName: 'Andrew Multilingual (English US - Natural Male)' },
  { name: 'Microsoft Server Speech Text to Speech Voice (en-US, JennyNeural)', shortName: 'en-US-JennyNeural', gender: 'Female', locale: 'en-US', friendlyName: 'Jenny (English US - Clear Female)' },
  { name: 'Microsoft Server Speech Text to Speech Voice (en-US, GuyNeural)', shortName: 'en-US-GuyNeural', gender: 'Male', locale: 'en-US', friendlyName: 'Guy (English US - Clear Male)' },
  { name: 'Microsoft Server Speech Text to Speech Voice (en-US, AriaNeural)', shortName: 'en-US-AriaNeural', gender: 'Female', locale: 'en-US', friendlyName: 'Aria (English US - Expressive Female)' },
  
  // Hindi Voices
  { name: 'Microsoft Server Speech Text to Speech Voice (hi-IN, MadhurNeural)', shortName: 'hi-IN-MadhurNeural', gender: 'Male', locale: 'hi-IN', friendlyName: 'Madhur (Hindi India - Male)' },
  { name: 'Microsoft Server Speech Text to Speech Voice (hi-IN, SwaraNeural)', shortName: 'hi-IN-SwaraNeural', gender: 'Female', locale: 'hi-IN', friendlyName: 'Swara (Hindi India - Female)' },
];

const TRUSTED_CLIENT_TOKEN = '6A5AA1D4EAFF4E9FB37E23D68491D6F4';
const EDGE_WS_URL = `wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=${TRUSTED_CLIENT_TOKEN}`;

function generateSecMsGec(): string {
  const unixNowSeconds = Math.floor(Date.now() / 1000);
  const winEpochSeconds = BigInt(unixNowSeconds + 11644473600);
  const winEpoch100Ns = winEpochSeconds * 10000000n;
  const roundedWinEpoch = winEpoch100Ns - (winEpoch100Ns % 3000000000n);
  const str = `${roundedWinEpoch}${TRUSTED_CLIENT_TOKEN}`;
  return crypto.createHash('sha256').update(str, 'ascii').digest('hex').toUpperCase();
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export interface EdgeTtsOptions {
  voice?: string;
  rate?: string; // e.g. "+0%", "+20%", "-10%"
  pitch?: string; // e.g. "+0Hz"
  volume?: string; // e.g. "+0%"
}

/**
 * Streams MP3 audio chunks generated by Microsoft Edge Neural TTS.
 * Calls onAudioChunk(buffer) as each chunk arrives in real-time.
 */
export function streamEdgeTts(
  text: string,
  options: EdgeTtsOptions = {},
  onAudioChunk: (chunk: Buffer) => void
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    if (!text || !text.trim()) {
      return reject(new Error('Text cannot be empty for Edge TTS'));
    }

    const voice = options.voice || 'bn-BD-PradeepNeural';
    const rate = options.rate || '+0%';
    const pitch = options.pitch || '+0Hz';
    const volume = options.volume || '+0%';

    const connectionId = crypto.randomUUID().replace(/-/g, '');
    const wsUrl = `${EDGE_WS_URL}&ConnectionId=${connectionId}`;

    const gec = generateSecMsGec();
    const headers = {
      'Pragma': 'no-cache',
      'Cache-Control': 'no-cache',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0',
      'Origin': 'chrome-extension://jdiccldimpdaibmpdkjnbmckianbfold',
      'Accept-Encoding': 'gzip, deflate, br',
      'Accept-Language': 'en-US,en;q=0.9',
      'Sec-MS-GEC': gec,
      'Sec-MS-GEC-Version': '1-131.0.2903.86',
    };

    const ws = new WebSocket(wsUrl, { headers });
    const audioChunks: Buffer[] = [];
    let isFinished = false;

    const timeout = setTimeout(() => {
      if (!isFinished) {
        isFinished = true;
        try { ws.close(); } catch {}
        if (audioChunks.length > 0) {
          resolve(Buffer.concat(audioChunks));
        } else {
          reject(new Error('Edge TTS request timed out'));
        }
      }
    }, 20000);

    ws.on('open', () => {
      // 1. Send speech.config
      const configMessage = `Content-Type:application/json; charset=utf-8\r\nPath:speech.config\r\n\r\n` +
        JSON.stringify({
          context: {
            synthesis: {
              audio: {
                metadataoptions: {
                  sentenceBoundaryEnabled: 'false',
                  wordBoundaryEnabled: 'false',
                },
                outputFormat: 'audio-24khz-48kbitrate-mono-mp3',
              },
            },
          },
        });
      ws.send(configMessage);

      // 2. Send SSML
      const requestId = crypto.randomUUID().replace(/-/g, '');
      const timestamp = new Date().toISOString();
      const escapedText = escapeXml(text.trim());
      const ssmlMessage = `X-RequestId:${requestId}\r\nContent-Type:application/ssml+xml\r\nX-Timestamp:${timestamp}Z\r\nPath:ssml\r\n\r\n` +
        `<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xml:lang='en-US'>` +
        `<voice name='${voice}'><prosody pitch='${pitch}' rate='${rate}' volume='${volume}'>` +
        `${escapedText}` +
        `</prosody></voice></speak>`;
      ws.send(ssmlMessage);
    });

    ws.on('message', (data: Buffer | string) => {
      if (typeof data === 'string') {
        if (data.includes('Path:turn.end')) {
          if (!isFinished) {
            isFinished = true;
            clearTimeout(timeout);
            try { ws.close(); } catch {}
            resolve(Buffer.concat(audioChunks));
          }
        }
      } else if (Buffer.isBuffer(data)) {
        if (data.length > 2) {
          const headerLength = data.readUInt16BE(0);
          if (data.length >= 2 + headerLength) {
            const headerStr = data.subarray(2, 2 + headerLength).toString('utf-8');
            if (headerStr.includes('Path:audio')) {
              const audioPayload = data.subarray(2 + headerLength);
              if (audioPayload.length > 0) {
                audioChunks.push(audioPayload);
                try {
                  onAudioChunk(audioPayload);
                } catch (err) {
                  console.error('[Edge TTS] onAudioChunk callback error:', err);
                }
              }
            }
          }
        }
      }
    });

    ws.on('error', (err) => {
      if (!isFinished) {
        isFinished = true;
        clearTimeout(timeout);
        if (audioChunks.length > 0) {
          resolve(Buffer.concat(audioChunks));
        } else {
          reject(err);
        }
      }
    });

    ws.on('close', () => {
      if (!isFinished) {
        isFinished = true;
        clearTimeout(timeout);
        resolve(Buffer.concat(audioChunks));
      }
    });
  });
}
